### ISSUE TITLE
Edit and right-click menus are strange

### ISSUE THREAD

**Issue by neilalexander** [ZasEditor/Zas-Editor-Issues#26]
Right-click menu orders "Copy" before "Cut" and has very few dividers that make it difficult for the eyes to follow the various Go language server options.

Edit global menu orders needs dividers between undo/redo and cut/copy/paste, like in most other apps.

**Comment by ZasEditor** [comment]
Hi Neil, thanks for the suggestion! You can expect an update with the fix next week
