### ISSUE TITLE
Terminal font letter spacing is broken when switching font to Fira Code

### ISSUE THREAD

**Issue by julesjacobs** [ZasEditor/Zas-Editor-Issues#29]
The terminal font rendering has lots of extra letter spacing when using Fira Code.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/476654/162455480-2ad22d01-f88f-4866-8dc1-a2f902937570.png">

**Comment by ZasEditor** [comment]
Thanks for the report. I was able to reproduce and fix the problem. There will be an update with this fix and many other small bug fixes next week.
