### ISSUE TITLE
Terminal font breaks when changing to fonts with ligatures

### ISSUE THREAD

**Issue by littlecastrum** [ZasEditor/Zas-Editor-Issues#34]
Selecting a font like `Dank Mono` or `Cartograph CF` breaks the terminal view and there is no configuration to fix this issue

**Comment by ZasEditor** [comment]
Thanks you so much for the bug report. If you're referring to the weird letter spacing, we fixed the issue; the update we're releasing next week won't have this bug. If it's something else, would you be able to provide a screenshot.

**Comment by littlecastrum** [comment]
Yeah it's a broad spacing issue that does not allow to make use of the terminal with those fonts

**Comment by ZasEditor** [comment]
We have fixed this issue. It will be fine in the next update we're releasing next week.
