### ISSUE TITLE
Little Typo: Documentation Exlporer should be Documentation Explorer

### ISSUE THREAD

**Issue by tamc** [ZasEditor/Zas-Editor-Issues#5]
Little Typo: Documentation Exlporer should be Documentation Explorer

![CleanShot 2022-04-08 at 06 37 11](https://user-images.githubusercontent.com/43987/162371546-498639df-4011-4fac-be62-939f7f2a94fd.png)

**Comment by ZasEditor** [comment]
Thanks, I just don't understand how we missed that 😭
